name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          pip install flet==0.19.0
          pip install "flet[all]"
          # إذا كان لديك مكتبات خارجية أخرى مستخدمة في views، أضفها هنا
          # pip install -r requirements.txt

      - name: Build APK
        run: |
          # استخدام النقطة يخبر Flet أن يبحث عن flet_config.toml و main.py في المجلد الحالي
          flet build apk .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pixel-pulse-apk
          path: build/apk/*.apk
