name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # إصدار مستقر
          channel: 'stable'

      - name: Install Dependencies
        run: |
          pip install flet
          flutter doctor # للتأكد من جاهزية البيئة

      - name: Build APK
        run: |
          # إضافة --no-interactive أو تمرير القيم مباشرة يحل مشكلة الـ EOF
          flet build apk --project "PixelPulse" --org "com.ageeel.pixel" --include-data "assets"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pixel-pulse-apk
          path: build/apk/*.apk
